In [ ]:
!pip install surprise

     |████████████████████████████████| 11.8 MB 5.0 MB/s 
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.1-cp37-cp37m-linux_x86_64.whl size=1619412 sha256=021bed3524e87db7fa1c510ad31853aa67c8e0ba07cca46cebc699c4db48392a
  Stored in directory: /root/.cache/pip/wheels/76/44/74/b498c42be47b2406bd27994e16c5188e337c657025ab400c1c
Successfully built scikit-surprise


## Loading Libraries

In [ ]:
import numpy as np
import pandas as pd
from scipy.sparse.linalg import svds
from surprise import Reader, Dataset, SVD
from surprise.model_selection import cross_validate
from surprise.model_selection import KFold

## Utilities

In [ ]:
dir_path = 'drive/MyDrive/ADM/movielens/'

In [ ]:
def movie_rec(y_bar, user_id, movies, y, num):
  user_row = user_id - 1
  sorted_preds = y_bar.iloc[user_row].sort_values(ascending=False)

  user_data = y[y.user_id == user_id]
  merged = user_data.merge(movies, how='left', left_on='movie_id', right_on='movie_id').sort_values(['rating'], ascending=False)

  res = movies[~movies['movie_id'].isin(merged['movie_id'])].merge(pd.DataFrame(sorted_preds).reset_index(), how = 'left', left_on = 'movie_id', right_on = 'movie_id').rename(columns = {user_row: 'Predictions'}).sort_values('Predictions', ascending = False).iloc[:num, :-1]

  return merged, res

## Loading Preprocessed Dataset

In [ ]:
ratings_data = pd.read_csv(dir_path + 'ratings_1.csv', encoding='latin-1')
ratings_data.drop(columns=['Unnamed: 0'], inplace=True)
users_data = pd.read_csv(dir_path + 'users_1.csv', encoding='latin-1')
users_data.drop(columns=['Unnamed: 0'], inplace=True)
movies_data = pd.read_csv(dir_path + 'movies_1.csv', encoding='latin-1')
movies_data.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
num_users = ratings_data['user_id'].drop_duplicates().max()
num_items = ratings_data['movie_id'].drop_duplicates().max()

In [ ]:
ratings_data.head()

user_id  movie_id  rating  timestamp  user_embeded_id  movie_embeded_id
0        1      1193       5  978300760                0              1192
1        1       661       3  978302109                0               660
2        1       914       3  978301968                0               913
3        1      3408       4  978300275                0              3407
4        1      2355       5  978824291                0              2354

In [ ]:
users_data.head()

user_id gender  age  occupation zipcode   age_enc               occ_enc
0        1      F    1          10   48067  Under 18          K-12 student
1        2      M   56          16   70072       56+         self-employed
2        3      M   25          15   55117     25-34             scientist
3        4      M   45           7   02460     45-49  executive/managerial
4        5      M   25          20   55455     25-34                writer

In [ ]:
movies_data.head()

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
ratings = ratings_data.pivot(index='user_id', columns='movie_id', values='rating').fillna(0)
ratings

movie_id  1     2     3     4     5     ...  3948  3949  3950  3951  3952
user_id                                 ...                              
1          5.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
2          0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
3          0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
4          0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
5          0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
...        ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...
6036       0.0   0.0   0.0   2.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
6037       0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
6038       0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
6039       0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
6040       3.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0

[6040 rows x 3706 columns]

In [ ]:
# de normalizing rating matrix
rating_matrix = ratings.values
mean_rating = np.mean(rating_matrix, axis=1)
rating_matrix = rating_matrix - mean_rating.reshape(-1, 1)

In [ ]:
rating_matrix

array([[ 4.94009714, -0.05990286, -0.05990286, ..., -0.05990286,
        -0.05990286, -0.05990286],
       [-0.12924987, -0.12924987, -0.12924987, ..., -0.12924987,
        -0.12924987, -0.12924987],
       [-0.05369671, -0.05369671, -0.05369671, ..., -0.05369671,
        -0.05369671, -0.05369671],
       ...,
       [-0.02050729, -0.02050729, -0.02050729, ..., -0.02050729,
        -0.02050729, -0.02050729],
       [-0.1287102 , -0.1287102 , -0.1287102 , ..., -0.1287102 ,
        -0.1287102 , -0.1287102 ],
       [ 2.6708041 , -0.3291959 , -0.3291959 , ..., -0.3291959 ,
        -0.3291959 , -0.3291959 ]])

## SVD - Support vector Decomposition

In [ ]:
# setting up SVD model
mu, sigma, vt = svds(rating_matrix, k = 50)

In [ ]:
sigma = np.diag(sigma)
sigma

array([[ 147.18581225,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,  147.62154312,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,  148.58855276, ...,    0.        ,
           0.        ,    0.        ],
       ...,
       [   0.        ,    0.        ,    0.        , ...,  574.46932602,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
         670.41536276,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        , 1544.10679346]])

In [ ]:
ratings_pred = np.dot(np.dot(mu, sigma), vt) + mean_rating.reshape(-1, 1)
ratings_pred

array([[ 4.28886061,  0.14305516, -0.1950795 , ...,  0.03191195,
         0.05044975,  0.08891033],
       [ 0.74471587,  0.16965927,  0.33541808, ..., -0.10110207,
        -0.0540982 , -0.14018846],
       [ 1.81882382,  0.45613623,  0.09097801, ...,  0.01234452,
         0.01514752, -0.10995596],
       ...,
       [ 0.61908871, -0.16176859,  0.10673806, ..., -0.01336948,
        -0.0303543 , -0.11493552],
       [ 1.50360483, -0.03620761, -0.16126817, ..., -0.01090407,
        -0.03864749, -0.16835943],
       [ 1.99624816, -0.18598715, -0.1564782 , ..., -0.00664061,
         0.12706713,  0.28500112]])

In [ ]:
pred_df = pd.DataFrame(ratings_pred, columns = ratings.columns)
pred_df

movie_id      1         2         3     ...      3950      3951      3952
0         4.288861  0.143055 -0.195080  ...  0.031912  0.050450  0.088910
1         0.744716  0.169659  0.335418  ... -0.101102 -0.054098 -0.140188
2         1.818824  0.456136  0.090978  ...  0.012345  0.015148 -0.109956
3         0.408057 -0.072960  0.039642  ... -0.026050  0.014841 -0.034224
4         1.574272  0.021239 -0.051300  ...  0.033830  0.125706  0.199244
...            ...       ...       ...  ...       ...       ...       ...
6035      2.392388  0.233964  0.413676  ...  0.271234  0.244983  0.734771
6036      2.070760  0.139294 -0.012666  ...  0.050798 -0.113427  0.033283
6037      0.619089 -0.161769  0.106738  ... -0.013369 -0.030354 -0.114936
6038      1.503605 -0.036208 -0.161268  ... -0.010904 -0.038647 -0.168359
6039      1.996248 -0.185987 -0.156478  ... -0.006641  0.127067  0.285001

[6040 rows x 3706 columns]

## Testing

In [ ]:
already_rated, new_preds = movie_rec(pred_df, 1310, movies_data, ratings_data, 20)

In [ ]:
already_rated

user_id  ...                             genres
5      1310  ...               Comedy|Drama|Romance
6      1310  ...                      Drama|Romance
7      1310  ...                    Drama|Film-Noir
15     1310  ...                              Drama
1      1310  ...                              Drama
12     1310  ...                           Thriller
11     1310  ...                           Thriller
20     1310  ...          Action|Comedy|Crime|Drama
18     1310  ...                       Comedy|Drama
17     1310  ...                              Drama
13     1310  ...                              Drama
23     1310  ...    Children's|Drama|Fantasy|Sci-Fi
10     1310  ...  Action|Adventure|Drama|Sci-Fi|War
9      1310  ...                              Drama
8      1310  ...               Comedy|Drama|Romance
4      1310  ...               Comedy|Drama|Romance
3      1310  ...                          Drama|War
16     1310  ...                             Comedy
19     1310  ...                          Drama|War
0      1310  ...                              Drama
14     1310  ...                              Drama
2      1310  ...                              Drama
21     1310  ...                              Drama
22     1310  ...                          Drama|War

[24 rows x 8 columns]

In [ ]:
new_preds

movie_id  ...                               genres
1618      1674  ...               Drama|Romance|Thriller
1880      1961  ...                                Drama
1187      1210  ...  Action|Adventure|Romance|Sci-Fi|War
1216      1242  ...                     Action|Drama|War
1202      1225  ...                                Drama
1273      1302  ...                                Drama
1220      1246  ...                                Drama
1881      1962  ...                                Drama
1877      1957  ...                                Drama
1938      2020  ...                        Drama|Romance
1233      1259  ...               Adventure|Comedy|Drama
3011      3098  ...                                Drama
2112      2194  ...                   Action|Crime|Drama
1876      1956  ...                                Drama
1268      1296  ...                        Drama|Romance
2267      2352  ...                         Comedy|Drama
1278      1307  ...                       Comedy|Romance
1165      1186  ...                                Drama
1199      1222  ...                     Action|Drama|War
2833      2919  ...                        Drama|Romance

[20 rows x 3 columns]

## Evaluation

In [ ]:
reader = Reader()
data = Dataset.load_from_df(ratings_data[['user_id', 'movie_id', 'rating']], reader)
model = SVD()

cross_validate(model, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.8733  0.8716  0.8737  0.8749  0.8748  0.8737  0.0012  
MAE (testset)     0.6847  0.6841  0.6857  0.6872  0.6873  0.6858  0.0013  
Fit time          47.64   48.24   48.75   48.73   48.73   48.42   0.43    
Test time         3.49    2.63    2.95    2.95    3.00    3.01    0.28    


{'fit_time': (47.63755226135254,
  48.23733425140381,
  48.747910499572754,
  48.73135757446289,
  48.727574825286865),
 'test_mae': array([0.68469391, 0.68414908, 0.6856898 , 0.68721239, 0.6873304 ]),
 'test_rmse': array([0.87329754, 0.87160043, 0.87370145, 0.87489552, 0.87482097]),
 'test_time': (3.4912829399108887,
  2.6339845657348633,
  2.9532926082611084,
  2.9537436962127686,
  2.996577024459839)}

## Train-Test split and model Validation

In [ ]:
training_set = data.build_full_trainset()
model.fit(training_set)

In [ ]:
ratings_data[ratings_data['user_id'] == 1500]

user_id  movie_id  ...  user_embeded_id  movie_embeded_id
248464     1500      3791  ...             1499              3790
248465     1500      3793  ...             1499              3792
248466     1500      2054  ...             1499              2053
248467     1500      1257  ...             1499              1256
248468     1500      2997  ...             1499              2996
...         ...       ...  ...              ...               ...
248574     1500      1223  ...             1499              1222
248575     1500      1080  ...             1499              1079
248576     1500      3911  ...             1499              3910
248577     1500      1230  ...             1499              1229
248578     1500      1240  ...             1499              1239

[115 rows x 6 columns]

In [ ]:
model.predict(1500, 1240)

Prediction(uid=1500, iid=1240, r_ui=None, est=4.118643758891733, details={'was_impossible': False})